name: SlimefunNukes
main: com.aurgiyalgo.SlimefunNukes.SlimefunNukes
version: 3.1
author: Joselu
description: Slimefun Addon which adds new explosives to your server
depend: [CS-CoreLib, Slimefun]

commands:
  sfnukes:
    permission: sfnukes.cmd

permissions:
  sfnukes.cmd:
    default: true