name: SlimefunNukes
main: com.aurgiyalgo.SlimefunNukes.SlimefunNukes
version: 3.2
author: Joselu
description: Slimefun Addon which adds new explosives to your server
depend: [Slimefun]
softdepend: [Towny, WorldGuard]
api-version: 1.16

commands:
  sfnukes:
    permission: sfnukes.cmd

permissions:
  sfnukes.cmd:
    default: true