name: SlimefunNuke
main: com.aurgiyalgo.SlimefunNukes.SlimefunNukes
version: 2.1
author: Joselu
description: Slimefun Addon which adds a few nukes to your server
depend: [CS-CoreLib, Slimefun]

commands:
  sfnukes:
    usage: <command> <argument>
    description: Commands for Slimefun Nukes

permissions:
  sfnukes.reload:
    description: Allows to reload the config files
    default: op
  sfnukes.version:
    description: Allows u to check the plugin versions