name: SlimefunNukes
main: com.aurgiyalgo.SlimefunNukes.SlimefunNukes
version: 2.1
author: Joselu
description: Slimefun Addon which adds a few nukes to your server
depend: [CS-CoreLib, Slimefun]

commands:
  sfnukes:
    permission: sfnukes.cmd

permissions:
  sfnukes.cmd:
    default: true